theme: jekyll-theme-minimal
title: Nambin Heo
description: |
  Senior Staff Software Engineer at Google
  PhD in Computer Graphics
  Enthusiast in Math and Science

resume_url: "https://www.dropbox.com/scl/fi/prhpdb38huddf6wwbd4ry/resume_nambinheo.pdf?rlkey=s8s25gjzakgpvezwyi8rhrh8t&e=2&st=feo3o3i4&dl=0"
github_url: "https://github.com/nambin"
linkedin_url: "https://www.linkedin.com/in/nambin-heo-9438a358"
youtube_url: "https://www.youtube.com/@NambinHeo"